return { athena = {
  name                = [[Athena]],
  description         = [[Airborne SpecOps Engineer]],
  acceleration        = 0.1,
  airStrafe           = 0,
  autoHeal            = 20,
  brakeRate           = 0.08,
  buildDistance       = 180,
  builder             = true,

  buildoptions        = {
    [[staticcon]],
    [[staticradar]],
    [[staticheavyradar]],
    [[staticjammer]],
    [[cloakcon]],
    [[spiderscout]],
    [[shieldraid]],
    [[hoverassault]],
    [[cloakheavyraid]],
    [[jumpskirm]],
    [[spiderskirm]],
    [[tankheavyraid]],
    [[cloakassault]],
    [[cloaksnipe]],
    [[vehheavyarty]],
    [[spiderantiheavy]],
    [[cloakaa]],
    [[shieldshield]],
    [[cloakjammer]],
    [[amphtele]],
    [[striderantiheavy]],
  },

  buildPic            = [[athena.png]],
  buildRange3D        = false,
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canResurrect        = true,
  canSubmerge         = false,
  category            = [[GUNSHIP UNARMED]],
  cloakCost           = 2,
  cloakCostMoving     = 5,
  collide             = true,
  corpse              = [[DEAD]],
  collisionVolumeOffsets = [[0 0 0]],
  collisionVolumeScales  = [[30 20 60]],
  collisionVolumeType    = [[ellipsoid]],
  selectionVolumeOffsets = [[0 0 0]],
  selectionVolumeScales  = [[45 20 75]],
  selectionVolumeType    = [[ellipsoid]],
  cruiseAltitude      = 80,

  customParams        = {
    airstrafecontrol = [[1]],
    modelradius    = [[15]],
    isfakefactory = 1,
    notreallyafactory = 1,
    select_show_eco = 1,
    sonar_can_be_disabled = 1,
    disable_radar_preview = 1,

    outline_x = 90,
    outline_y = 90,
    outline_yoff = 12,
  },

  explodeAs           = [[GUNSHIPEX]],
  fireState           = 0,
  floater             = true,
  footprintX          = 2,
  footprintZ          = 2,
  health              = 750,
  hoverAttack         = true,
  iconType            = [[t3builder]],
  initCloaked         = false,
  maxSlope            = 36,
  metalCost           = 600,
  minCloakDistance    = 125,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET]],
  objectName          = [[selene.s3o]],
  radarDistance       = 1200,
  radarDistanceJam    = 300,
  script              = [[athena.lua]],
  selfDestructAs      = [[GUNSHIPEX]],
  showNanoSpray       = false,
  sightDistance       = 380,
  sonarDistance       = 600,
  speed               = 210,
  resurrectSpeed      = 7.5,
  turnRate            = 148,
  workerTime          = 15,

 weapons                = {
    {
      def                = [[NANO_PLAGUE_MISSILE]],
      badTargetCategory  = [[SWIM LAND SUB SHIP HOVER GUNSHIP FIXEDWING]],
      onlyTargetCategory = [[SWIM LAND SUB SINK TURRET FLOAT SHIP HOVER GUNSHIP FIXEDWING]],
    },
 },
  
 weaponDefs          = {

    NANO_PLAGUE_MISSILE = {
      name                    = [[Nanoplague Canister]],
      areaOfEffect            = 280,
      cegTag                  = [[seismictrail]],
      craterBoost             = 1,
      craterMult              = 1.4,
      
      customParams        = {
        apply_nano_plague     = "1",
        force_ignore_ground = [[1]],

        light_camera_height = 3000,
        light_color = [[1 0.58 0.17]],
        light_radius = 200,
      },
      
      damage                  = {
        default = 20,
      },
      
      edgeEffectiveness       = 1,
      explosionGenerator      = [[custom:bull_fade]]--[[custom:greencannonimpact]],
      fireStarter             = 70,
      flightTime              = 3.1,
      impulseBoost            = 0.75,
      impulseFactor           = 0.3,
      interceptedByShieldType = 2,
      leadlimit               = 0,
      model                   = [[wep_merl.s3o]],
      range                   = 440,
      reloadtime              = 60,
      smokeTrail              = true,
      soundHit                = [[weapon/aoe_aura2]],
      soundHitVolume          = 15,
      soundStart              = [[weapon/missile/rapid_rocket_fire2]],
      soundStartVolume        = 7,
      startVelocity           = 230,
      texture2                = [[lightsmoketrail]],
      tracks                  = true,
      trajectoryHeight        = 0.4,
      turnRate                = 21000,
      turret                  = true,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 230,
    },
    
  },
  
  featureDefs         = {

    DEAD  = {
      blocking         = true,
      featureDead      = [[HEAP]],
      footprintX       = 2,
      footprintZ       = 2,
      collisionVolumeOffsets = [[0 0 0]],
      collisionVolumeScales  = [[30 20 60]],
      collisionVolumeType    = [[ellipsoid]],
      object           = [[selene_dead.s3o]],
    },

    HEAP  = {
      blocking         = false,
      footprintX       = 2,
      footprintZ       = 2,
      object           = [[debris2x2c.s3o]],
    },

  },

} }
