return { bomberheron= {
  name                = [[Heron]],
  description         = [[Strafing Strikecraft]],
  brakerate           = 0.4,
  builder             = false,
  buildPic            = [[bomberstrike.png]],
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canLoopbackAttack   = true,
  canPatrol           = true,
  canSubmerge         = false,
  category            = [[FIXEDWING]],
  collide             = false,
  collisionVolumeOffsets = [[0 2 0]],
  collisionVolumeScales  = [[50 16 80]],
  collisionVolumeType    = [[ellipsoid]],
  corpse              = [[DEAD]],
  cruiseAltitude      = 160,

  customParams        = {
    reallyabomber    = [[1]],
    reammoseconds    = [[10]],
    refuelturnradius = [[150]],
    modelradius      = [[10]],
    okp_damage       = 340, -- Not perfectly reliable
    can_set_target   = [[1]],
    from_factory     = nil,
  },

  explodeAs           = [[GUNSHIPEX]],
  floater             = true,
  footprintX          = 3,
  footprintZ          = 3,
  health              = 900,
  iconType            = [[bomberskirm]],
  maxAcc              = 0.5,
  maxAileron          = 0.025,
  maxBank             = 0.55,
  maxElevator         = 0.01,
  maxRudder           = 0.007,
  maxFuel             = 1000000,
  metalCost           = 220,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP]],
  objectName          = [[bomberstrike.s3o]],
  script              = [[bomberheron.lua]],
  selfDestructAs      = [[GUNSHIPEX]],

  sfxtypes            = {},
  sightDistance       = 780,
  speed               = 252,
  turnRadius          = 500,
  workerTime          = 0,

  weapons             = {
    {
      def                = [[DISPLOSABLE_CANNONS]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 70,
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER SINK SUB]],
    },
  },


  weaponDefs          = {
  
    DISPLOSABLE_CANNONS = {
      name                    = [[Disposable Pod EMG]],
      accuracy                = 0,
      alphaDecay              = 0.7,
      areaOfEffect            = 75,
      burnblow                = false,
      burst                   = 10,
      burstrate               = 2/30,
      cegTag                  = [[hmg_trail_light]],
      craterBoost             = 0.15,
      craterMult              = 0.3,

      customParams        = {
        burst = Shared.BURST_UNRELIABLE,
        reammoseconds = "autogenerated in posts",
        
        --light_color = [[0.8 0.76 0.38]],
        light_radius = 50,
      },

      damage                  = {
        default = 33,
        planes  = 33,
      },

      edgeEffectiveness       = 0.5,
      explosionGenerator      = [[custom:EMG_HIT_HE]],
      firestarter             = 70,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      intensity               = 0.7,
      interceptedByShieldType = 1,
      noSelfDamage            = true,
      projectiles             = 2,
      range                   = 450,
      reloadtime              = 0.5,
      rgbColor                = [[1 0.95 0.4]],
      separation              = 1.5,
      soundHit                = [[weapon/cannon/emg_hit]],
      soundStart              = [[weapon/heavy_emg]],
      sprayAngle              = 1000,
      stages                  = 10,
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 580,
    },
  },


  featureDefs         = {

    DEAD  = {
      blocking         = true,
      featureDead      = [[HEAP]],
      footprintX       = 2,
      footprintZ       = 2,
      object           = [[bomberstrike_dead.s3o]],
    },

    HEAP  = {
      blocking         = false,
      footprintX       = 2,
      footprintZ       = 2,
      object           = [[debris2x2c.s3o]],
    },

  },

} }
