return { bomberfalcon = {
  name                = [[Falcon]],
  description         = [[Rocket Strike Bomber]],
  brakerate           = 0.4,
  builder             = false,
  buildPic            = [[bomberstrike.png]],
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canSubmerge         = false,
  category            = [[FIXEDWING]],
  collide             = false,
  collisionVolumeOffsets = [[0 2 0]],
  collisionVolumeScales  = [[50 16 80]],
  collisionVolumeType    = [[ellipsoid]],
  corpse              = [[DEAD]],
  cruiseAltitude      = 160,

  customParams        = {
    reallyabomber    = [[1]],
    reammoseconds    = [[10]],
    refuelturnradius = [[150]],
    modelradius      = [[10]],
    okp_damage       = 340, -- Not perfectly reliable
    can_set_target   = [[1]],
    from_factory     = nil,
    
    combat_slowdown = 0.6,
  },

  explodeAs           = [[GUNSHIPEX]],
  floater             = true,
  footprintX          = 3,
  footprintZ          = 3,
  health              = 900,
  iconType            = [[bomberskirm]],
  maxAcc              = 0.5,
  maxAileron          = 0.025,
  maxBank             = 0.55,
  maxElevator         = 0.01,
  maxRudder           = 0.007,
  maxFuel             = 1000000,
  metalCost           = 220,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP]],
  objectName          = [[bomberstrike.s3o]],
  script              = [[bomberfalcon.lua]],
  selfDestructAs      = [[GUNSHIPEX]],

  sfxtypes            = {},
  sightDistance       = 780,
  speed               = 252,
  turnRadius          = 500,
  workerTime          = 0,

  weapons             = {
    {
      def                = [[STORM_ROCKET]],
      badTargetCategory  = [[FIXEDWING]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 50,
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER SINK SUB]],
    },
  },


  weaponDefs          = {
  
    STORM_ROCKET = {
      accuracy                = 000,
      name                    = [[Storm Rocketpods]],
      areaOfEffect            = 48,
      burnblow                = true,
      burst                   = 2,
      burstrate               = 0.2,
      cegTag                  = [[rocket_trail_bar]],
      craterBoost             = 1,
      craterMult              = 2,
      collideFriendly         = false, --Other solution to magpies shooting themselves?

      customParams        = {
        reammoseconds = "autogenerated in posts",
        --light_camera_height = 1800,
        light_radius = 100,
        

      },
      
      damage                  = {
        default = 100,
      },
      
      dance                   = 0,
      edgeEffectiveness       = 0.6,
      --explosionGenerator      = [[custom:xamelimpact]],
      fireStarter             = 70,
      flightTime              = 2,
      impulseBoost            = 200,
      impulseFactor           = 0.5,
      interceptedByShieldType = 2,
      model                   = [[wep_m_ajax.s3o]],
      myGravity               = 0.15,
      projectiles             = 1,
      noSelfDamage            = true,
      range                   = 600,
      reloadtime              = 0.4,
      smokeTrail              = true,
      selfExplode             = true,
      soundHit                = [[weapon/missile/sabot_hit]],  
      soundHitVolume          = 8,
      soundStart              = [[weapon/missile/sabot_fire]],
      soundStartVolume        = 7,
      startVelocity           = 500,
      sprayAngle              = 1500,
      tracks                  = false,
      trajectoryHeight        = 0.1,
      turret                  = true,
      weaponAcceleration      = 250,
      weaponType              = [[MissileLauncher]],
      maxVelocity             = 500,
      wobble                  = 000,
    },
    
    
  },


  featureDefs         = {

    DEAD  = {
      blocking         = true,
      featureDead      = [[HEAP]],
      footprintX       = 2,
      footprintZ       = 2,
      object           = [[bomberstrike_dead.s3o]],
    },

    HEAP  = {
      blocking         = false,
      footprintX       = 2,
      footprintZ       = 2,
      object           = [[debris2x2c.s3o]],
    },

  },

} }
