return { bomberstrike = {
  name                = [[Magpie]],
  description         = [[Tactical Strike Bomber]],
  brakerate           = 0.4,
  builder             = false,
  buildPic            = [[bomberstrike.png]],
  canFly              = true,
  canGuard            = true,
  canLoopbackAttack   = true,
  canMove             = true,
  canPatrol           = true,
  canSubmerge         = false,
  category            = [[FIXEDWING]],
  collide             = false,
  collisionVolumeOffsets = [[0 2 0]],
  collisionVolumeScales  = [[50 16 80]],
  collisionVolumeType    = [[ellipsoid]],
  corpse              = [[DEAD]],
  cruiseAltitude      = 160,

  customParams        = {
    reallyabomber    = [[1]],
    reammoseconds    = [[10]],
    refuelturnradius = [[150]],
    modelradius      = [[10]],
    okp_damage       = 340, -- Not perfectly reliable
    can_set_target   = [[1]],
    from_factory     = nil,
  },

  explodeAs           = [[GUNSHIPEX]],
  floater             = true,
  footprintX          = 3,
  footprintZ          = 3,
  health              = 900,
  iconType            = [[bomberskirm]],
  maxAcc              = 0.5,
  maxAileron          = 0.025,
  maxBank             = 0.55,
  maxElevator         = 0.01,
  maxRudder           = 0.007,
  maxFuel             = 1000000,
  metalCost           = 220,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP]],
  objectName          = [[bomberstrike.s3o]],
  script              = [[bomberstrike.lua]],
  selfDestructAs      = [[GUNSHIPEX]],

  sfxtypes            = {},
  sightDistance       = 780,
  speed               = 252,
  turnRadius          = 500,
  workerTime          = 0,

  weapons             = {
    {
      def                = [[STORM_ROCKET]],
      badTargetCategory  = [[FIXEDWING]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 70,
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER SINK SUB]],
    },
  },


  weaponDefs          = {
  
    STORM_ROCKET = {
      accuracy                = 2000,
      name                    = [[Heavy Rocket]],
      areaOfEffect            = 200,
      cegTag                  = [[rocket_trail_bar_flameboosted]],
      craterBoost             = 1,
      craterMult              = 2,
      collideFriendly         = false, --Other solution to magpies shooting themselves?

      customParams        = {
        burst = Shared.BURST_UNRELIABLE,
        reammoseconds = "autogenerated in posts",
        light_camera_height = 1800,
      },
      
      damage                  = {
        default = 180,
      },
      
      dance                   = 40,
      edgeEffectiveness       = 0.6,
      explosionGenerator      = [[custom:xamelimpact]],
      fireStarter             = 70,
      flightTime              = 0.5,
      impulseBoost            = 0.75,
      impulseFactor           = 0.4,
      interceptedByShieldType = 2,
      model                   = [[corbanishrk.s3o]],
      myGravity               = 0.15,
      projectiles             = 2,
      noSelfDamage            = true,
      predictBoost            = 0.75,
      range                   = 550,
      reloadtime              = 1,
      smokeTrail              = true,
      selfExplode             = true,
      soundHit                = [[weapon/bomb_hit]],
      soundHitVolume          = 8,
      soundStart              = [[weapon/missile/missile2_fire_bass]],
      soundStartVolume        = 7,
      startVelocity           = 350,
      sprayAngle              = 2000,
      tracks                  = false,
      trajectoryHeight        = 0.5,
      turret                  = true,
      weaponType              = [[MissileLauncher]],
      maxVelocity             = 350,
      wobble                  = 5000,
    },
    
    
  },


  featureDefs         = {

    DEAD  = {
      blocking         = true,
      featureDead      = [[HEAP]],
      footprintX       = 2,
      footprintZ       = 2,
      object           = [[bomberstrike_dead.s3o]],
    },

    HEAP  = {
      blocking         = false,
      footprintX       = 2,
      footprintZ       = 2,
      object           = [[debris2x2c.s3o]],
    },

  },

} }
